import { defineConfig } from "tsup";
import { readFileSync } from "node:fs";

const APP_VERSION = JSON.stringify(
  JSON.parse(readFileSync(new URL("./package.json", import.meta.url), "utf8")).version,
);

export default defineConfig([
  {
    entry: { collector: "src/collector.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    define: {
      __APP_VERSION__: APP_VERSION,
    },
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { "fetch-quota-bg": "src/fetch-quota-bg.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    define: {
      __APP_VERSION__: APP_VERSION,
    },
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { "hourly-maintenance-bg": "src/hourly-maintenance-bg.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    define: {
      __APP_VERSION__: APP_VERSION,
    },
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { aggregate: "src/aggregate-entry.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    define: {
      __APP_VERSION__: APP_VERSION,
    },
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { mcp: "src/mcp/server.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    define: {
      __APP_VERSION__: APP_VERSION,
    },
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { tui: "src/tui/entry.tsx" },
    outDir: "bin",
    format: "esm",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    define: {
      __APP_VERSION__: APP_VERSION,
    },
    noExternal: [/.*/],
    banner: {
      js: '#!/usr/bin/env node\nimport { createRequire } from "node:module";\nconst require = createRequire(import.meta.url);',
    },
    clean: false,
  },
  {
    entry: { "plugin-setup": "src/plugin-setup.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    define: {
      __APP_VERSION__: APP_VERSION,
    },
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
]);
