import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: { collector: "src/collector.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { "fetch-quota-bg": "src/fetch-quota-bg.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { "hourly-maintenance-bg": "src/hourly-maintenance-bg.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { aggregate: "src/aggregate-entry.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { mcp: "src/mcp/server.ts" },
    outDir: "bin",
    format: "cjs",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    noExternal: [/.*/],
    banner: { js: "#!/usr/bin/env node" },
    clean: false,
  },
  {
    entry: { tui: "src/tui/entry.tsx" },
    outDir: "bin",
    format: "esm",
    target: "node20",
    platform: "node",
    bundle: true,
    minify: false,
    sourcemap: false,
    external: ["react", "ink"],
    clean: false,
  },
]);
